### ISSUE TITLE
[Feature request] Please add an official AdoptOpenJDK GitHub Action.

### ISSUE THREAD

**Issue by sblantipodi** [AdoptOpenJDK/openjdk-build#2096]
As title.
Please consider to add an official AdoptOpenJDK GitHub Action.

Thanks
Davide

**Comment by sophia-guo** [comment]
https://github.com/AdoptOpenJDK/build-jdk

**Comment by sophia-guo** [comment]
@sblantipodi what's your use case for this action?

**Comment by sblantipodi** [comment]
thanks for the answer @sophia-guo 
love AdoptOpenJDK, your "free" support is incredible.

I would like to have the same action I use for OpenJDK:
```
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.x.x'
```
https://github.com/marketplace/actions/setup-java-jdk

a simple action that setup JDK on my workflow.

I will look in your link and how to use it, thanks!

**Comment by sophia-guo** [comment]
For setup-java you can use https://github.com/AdoptOpenJDK/install-jdk

**Comment by sblantipodi** [comment]
WOW! thank you for the help!
closing the issue, thanks!

**Comment by sblantipodi** [comment]
just last question @sophia-guo if I can.
why this action is not present here?
https://github.com/marketplace?query=adopt

**Comment by sophia-guo** [comment]
@karianna may have answer?

**Comment by smlambert** [comment]
We had not yet put these github actions in the marketplace as they are still being enhanced/improved, but certainly the plan was to likely do so at some point, including the [run-aqa action](https://github.com/AdoptOpenJDK/run-aqa) that enables developers to run tests against a freshly built or freshly installed binary.  It will need to be discussed and be agreed upon by the [TSC](https://github.com/AdoptOpenJDK/TSC#current-members).  I can add it to our next meeting's agenda.

**Comment by sblantipodi** [comment]
hi @sophia-guo but does the setup action works on macos?
```
    - name: Set up AdoptOpenJDK 15
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '15'
        architecture: x64
```

using this but when I run
java -version
I see the JDK 1.8 version

should that action set the JDK15 as the default JDK?
