### ISSUE TITLE
openjdk10 builds on CentOS6 are failing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#265]
It looks like it's now using the default gcc 4.4.7 instead of the gcc 4.8.2 in `/opt/devtoolset-2` Somehow it was picking up the 4.8.2 on the CentOS boxes up until the 16th

Last good build was https://ci.adoptopenjdk.net/job/openjdk10_build_x86-64_linux/119/console and contained this, suggesting there might have been a `/usr/bin/gcc -> /opt/devtoolset-2/root/usr/bin/gcc` symbolic link in place (/opt/devtoolset-2 is where the official 4.8 gcc goes on RHEL/CentOS6)

```
configure: Using default toolchain gcc (GNU Compiler Collection)
checking for gcc... /usr/bin/gcc
checking resolved symbolic links for CC... /data/opt/rh/devtoolset-2/root/usr/bin/gcc
configure: Using gcc C compiler version 4.8.2 [gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

The /usr/bin/gcc on `build-digitalocean-centos69-x64-1` was put in place on March 13s at 18:49 local time and the corresponding package `gcc-4.4.7-18.el6_9.2.x86_64` was installed on March 15th which would be consistent with when it started breaking. Same on Friday 16th on `build-joyent-centos69-64-1` (which would have been due to the `yum update` cron that we have to keep the systems patched based on the install timestamps)

The ansible playbook had previously put a symlink in place to make 4.8.4 the default:

```
- name: Create symlink for /opt/rh/devtoolset-2/root/usr/bin/gcc to gcc
  file:
    src: /opt/rh/devtoolset-2/root/usr/bin/gcc
    dest: /usr/bin/gcc
    force: true
    owner: root
    group: root
    state: link
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
  tags: build_tools
```
I think my preferred solution is not to put the symlink in place, and set CC/CXX variables somewhere to force it to 4.8. Alternatively we could put the `devtoolset-2` bin directory in the path before /usr/bin. Thoughts?
